# Generated by Django 4.2a1 on 2025-02-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
